name: Auto Publish Robot

on:
  schedule:
    # Cứ mỗi 30 phút chạy 1 lần (giờ UTC)
    - cron: '*/30 * * * *'
  workflow_dispatch: # Cho phép bấm chạy bằng tay để test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas gspread google-auth pytz requests

      - name: Run publish script
        env:
          service_account: ${{ secrets.service_account }}
        run: python auto_publish.py
