name: Auto Publish Robot

on:
  schedule:
    # Nhịp tim 5 phút/lần (Lùa cá cực kỳ sát giờ)
    - cron: '*/5 * * * *'
  workflow_dispatch: # Vẫn giữ nút bấm tay để Sếp thích là test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas gspread google-auth pytz requests

      - name: Run publish script
        env:
          service_account: ${{ secrets.service_account }}
        run: python auto_publish.py
